apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: nomulus
deploy:
  kubectl:
    manifests:
    - proxy/kubernetes/proxy-deployment-alpha.yaml
    - proxy/kubernetes/proxy-deployment-crash-canary.yaml
    - proxy/kubernetes/proxy-deployment-crash.yaml
    - proxy/kubernetes/proxy-deployment-production-canary.yaml
    - proxy/kubernetes/proxy-deployment-production.yaml
    - proxy/kubernetes/proxy-deployment-sandbox-canary.yaml
    - proxy/kubernetes/proxy-deployment-sandbox.yaml
    - proxy/kubernetes/proxy-service-canary.yaml
    - proxy/kubernetes/proxy-service.yaml
