# This will sync the configuration files in the internal repo with their
# corresponding objects in the database.
#
# To manually trigger a build on GCB, run:
# gcloud builds submit --config cloudbuild-sync-db-objects.yaml --substitutions \
#   _INTERNAL_REPO_URL=[URL] ..
#
# To trigger a build automatically, follow the instructions below and add a trigger:
# https://cloud.google.com/cloud-build/docs/running-builds/automate-builds
#
# Note that the release process hardens the tags and variables in this file:
# - The 'latest' tag on docker images will be replaced by their image digests.
# - The ${_ENV} pattern will be replaced by the actual environment name.
# Please refer to ./cloudbuild-release.yaml for more details.
#
steps:
# Check out the internal repo.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    git clone https://gerrit.googlesource.com/gcompute-tools
    ./gcompute-tools/git-cookie-authdaemon
    git clone ${_INTERNAL_REPO_URL} nomulus-internal
# Download and decrypt the nomulus tool credential
- name: 'gcr.io/$PROJECT_ID/builder:latest'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    set -e
    gcloud secrets versions access latest \
      --secret nomulus-tool-cloudbuild-credential \
      > nomulus_tool_credential.json
# Configure the TLDs using the stored configuration files in the internal repo
- name: 'gcr.io/$PROJECT_ID/db_object_updater:latest'
  args:
  - ${_ENV}
  - ./nomulus_tool_credential.json
  - nomulus-internal/core/src/main/java/google/registry/config/files/tld/
  - configure_tld
# Configure the premium lists using the stored configuration files in the internal repo
- name: 'gcr.io/$PROJECT_ID/db_object_updater:latest'
  args:
  - ${_ENV}
  - ./nomulus_tool_credential.json
  - nomulus-internal/core/src/main/java/google/registry/config/files/premium/
  - update_premium_list
#TODO(sarahbot@): Uncomment out reserved lists step once go/r3pr/2292 is deployed and
#kokoro presubmit tests are added for reserved lists
# Configure the reserved lists using the stored configuration files in the internal repo
#- name: 'gcr.io/$PROJECT_ID/db_object_updater:latest'
#  args:
#  - ${_ENV}
#  - ./nomulus_tool_credential.json
#  - nomulus-internal/core/src/main/java/google/registry/config/files/reserved/
#  - update_reserved_list

timeout: 7200s
options:
  machineType: 'E2_HIGHCPU_32'
